version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - APP_UPLOAD_DIR=/app/uploads
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
